[build]
builder = "nixpacks"

[deploy]
startCommand = "node server/server.js"
healthcheckPath = "/"
healthcheckTimeout = 180
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[build.env]
NODE_ENV = "production"
